global.HTTP_OK = 200;
global.HTTP_CREATED = 201;
global.HTTP_NO_CONTENT = 204;
global.HTTP_BAD_REQUEST = 400;
global.HTTP_UNAUTHORIZED = 401;
global.HTTP_FORBIDDEN = 403;
global.HTTP_NOT_FOUND = 404;
global.HTTP_INTERNAL_SERVER_ERROR = 500;
